baseURL = 'https://sunnyhh.github.io/photography/'
languageCode = 'en-us'
title = 'Photography Portfolio - Sunny'
theme = 'hugo-gallery'

# Build optimization
[build]
  writeStats = true
  noChmod = true
  noTimes = true

[params]
  title = "Sunny's Photography"
  description = "Aviation, travel, and everyday moments captured through my lens"
  customCSS = ["css/custom.css"]
  
[params.author]
  name = "Ge (Sunny) Li"
  email = "sunnyhh051008@gmail.com"
  
[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "Home"
    url = "https://sunnyhh.github.io"
    weight = 1

  [[menu.main]]
    name = "Photography"
    url = '/'
    weight = 2

  [[menu.main]]
    name = "Aviation"
    url = "/aviation/"
    weight = 3

  [[menu.main]]
    name = "Cityscapes"
    url = "/cityscapes/"
    weight = 4